spring.application.name=ngoApp

# Database Configuration (Hardcoded for Render/Docker)
spring.datasource.url=jdbc:mysql://ngo-db:3306/ngo
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=9090

# Twilio Secrets (Hardcoded as requested)
twilio.sid=ACe37dbea2840bc5bdee0f5e9a728c6062
twilio.token=c595a6b20bf9ca8d3b72c745d1d9228b
twilio.whatsapp=whatsapp:+14155238886

app.base.url=https://ngo-volunteer-app.onrender.com

# Admin credentials
admin.email=admin@rsai.org
admin.password=admin123
